# 予想
1 2 3 ... 9 と出力されたのちに、実行エラーが発生する

# 結果の説明
予想通りの結果となった。関数内の 変数i は関数の中でのみ有効なため、ループ変数i に影響を与えなかった。
また、 ループ変数i はループ内で有効なローカル変数のため、最後の行の console.log() でエラーが発生した。

# var に変えた場合の予想
1 2 3 ... 9 と出力されたのちに、10が出力される

# 結果の説明
予想通りの結果となった。ループ変数i は var で宣言することでグローバル変数となり、実行エラーが発生しなかった。